import { Task, TaskStep } from '@/types'

// README 내용 생성
export function generateReadmeContent(task: Task): string {
  const steps = task.steps || []
  const successCriteria = task.success_criteria || []
  const techStack = task.tech_stack || []

  const difficultyLabel =
    task.difficulty === 'beginner' ? '🟢 초급' :
    task.difficulty === 'intermediate' ? '🟡 중급' :
    '🔴 고급'

  return `# ${task.title}

> Lecpin 실습 과제

## 📋 과제 개요

${task.description}

### 왜 이 과제인가요?

${task.reason}

---

## 🎯 학습 목표

이 과제를 완료하면 다음을 할 수 있게 됩니다:

${successCriteria.map((c: string, i: number) => `${i + 1}. ${c}`).join('\n')}

---

## 🛠 기술 스택

${techStack.map((t: string) => `- ${t}`).join('\n')}

---

## 📝 구현 단계

${steps.map((step: TaskStep, i: number) => `
### Step ${step.order || i + 1}${step.title ? `: ${step.title}` : ''}

${step.content}
`).join('\n')}

---

## ⏱ 예상 소요 시간

${task.estimated_time}

## 📊 난이도

${difficultyLabel}

---

## ⚠️ 중요 안내

> **코드 분량 제한**: AI 코드 리뷰의 정확도를 위해 **핵심 파일 3~5개, 총 300줄 이내**로 작성해주세요.
>
> 너무 많은 파일이나 코드를 제출하면 리뷰 품질이 저하될 수 있습니다.
> 보일러플레이트보다 **핵심 로직 구현**에 집중해주세요!

---

## 🚀 시작하기

1. 이 레포지토리를 클론합니다
2. 필요한 패키지를 설치합니다
3. 위의 구현 단계를 따라 진행합니다
4. 완료 후 Lecpin에서 제출합니다

---

<p align="center">
  <sub>Generated by <a href="https://lecpin.com">Lecpin</a></sub>
</p>
`
}

// GitHub 레포지토리 README 업데이트
export async function updateRepoReadme(params: {
  repoUrl: string
  githubToken: string
  task: Task
}): Promise<{ success: boolean; error?: string }> {
  const { repoUrl, githubToken, task } = params

  try {
    // 레포 정보 추출 (예: https://github.com/username/repo)
    const repoUrlParts = repoUrl.split('/')
    const repoName = repoUrlParts[repoUrlParts.length - 1]
    const owner = repoUrlParts[repoUrlParts.length - 2]

    // README 내용 생성
    const readmeContent = generateReadmeContent(task)

    // 기존 README 파일 정보 가져오기 (sha 필요)
    const getFileRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/README.md`,
      {
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
      }
    )

    let sha: string | undefined
    if (getFileRes.ok) {
      const fileData = await getFileRes.json()
      sha = fileData.sha
    }

    // README 업데이트
    const updateRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/README.md`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
        body: JSON.stringify({
          message: 'docs: Update README with task requirements',
          content: Buffer.from(readmeContent).toString('base64'),
          ...(sha && { sha }),
        }),
      }
    )

    if (!updateRes.ok) {
      const errorData = await updateRes.json()
      console.error('GitHub README update error:', errorData)
      return { success: false, error: 'README 업데이트에 실패했습니다.' }
    }

    return { success: true }
  } catch (error) {
    console.error('README update error:', error)
    return { success: false, error: '서버 오류가 발생했습니다.' }
  }
}
