import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { Task, TaskStep } from '@/types'

interface Params {
  params: Promise<{ id: string }>
}

export async function PUT(request: Request, { params }: Params) {
  try {
    const supabase = await createClient()
    const { id: taskId } = await params

    // 인증 확인
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: '로그인이 필요합니다.' }, { status: 401 })
    }

    // 사용자 정보 (GitHub 토큰) 가져오기
    const { data: profile, error: profileError } = await supabase
      .from('users')
      .select('github_token, github_username')
      .eq('id', user.id)
      .single()

    if (profileError || !profile?.github_token) {
      return NextResponse.json({ error: 'GitHub 토큰이 없습니다.' }, { status: 401 })
    }

    // 과제 정보 가져오기
    const { data: task, error: taskError } = await supabase
      .from('tasks')
      .select('*, lectures(*)')
      .eq('id', taskId)
      .single()

    if (taskError || !task) {
      return NextResponse.json({ error: '과제를 찾을 수 없습니다.' }, { status: 404 })
    }

    if (!task.github_repo_url) {
      return NextResponse.json({ error: '연결된 GitHub 레포지토리가 없습니다.' }, { status: 400 })
    }

    // 레포 이름 추출 (예: https://github.com/username/repo -> repo)
    const repoUrlParts = task.github_repo_url.split('/')
    const repoName = repoUrlParts[repoUrlParts.length - 1]
    const owner = repoUrlParts[repoUrlParts.length - 2]

    // README 내용 생성
    const readmeContent = generateReadmeContent(task as unknown as Task)

    // 기존 README 파일 정보 가져오기 (sha 필요)
    const getFileRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/README.md`,
      {
        headers: {
          'Authorization': `Bearer ${profile.github_token}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
      }
    )

    let sha: string | undefined
    if (getFileRes.ok) {
      const fileData = await getFileRes.json()
      sha = fileData.sha
    }

    // README 업데이트
    const updateRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/README.md`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${profile.github_token}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
        body: JSON.stringify({
          message: 'Update README with task details',
          content: Buffer.from(readmeContent).toString('base64'),
          ...(sha && { sha }),
        }),
      }
    )

    if (!updateRes.ok) {
      const errorData = await updateRes.json()
      console.error('GitHub API error:', errorData)
      return NextResponse.json({ error: 'README 업데이트에 실패했습니다.' }, { status: 500 })
    }

    return NextResponse.json({ success: true })

  } catch (error) {
    console.error('README update error:', error)
    return NextResponse.json({ error: '서버 오류가 발생했습니다.' }, { status: 500 })
  }
}

function generateReadmeContent(task: Task): string {
  const steps = task.steps || []
  const successCriteria = task.success_criteria || []
  const techStack = task.tech_stack || []

  const difficultyLabel =
    task.difficulty === 'beginner' ? '🟢 초급' :
    task.difficulty === 'intermediate' ? '🟡 중급' :
    '🔴 고급'

  return `# ${task.title}

> Lecpin 실습 과제

## 📋 과제 개요

${task.description}

### 왜 이 과제인가요?

${task.reason}

---

## 🎯 학습 목표

이 과제를 완료하면 다음을 할 수 있게 됩니다:

${successCriteria.map((c: string, i: number) => `${i + 1}. ${c}`).join('\n')}

---

## 🛠 기술 스택

${techStack.map((t: string) => `- ${t}`).join('\n')}

---

## 📝 구현 단계

${steps.map((step: TaskStep, i: number) => `
### Step ${step.order || i + 1}${step.title ? `: ${step.title}` : ''}

${step.content}
`).join('\n')}

---

## ⏱ 예상 소요 시간

${task.estimated_time}

## 📊 난이도

${difficultyLabel}

---

## 🚀 시작하기

1. 이 레포지토리를 클론합니다
2. 필요한 패키지를 설치합니다
3. 위의 구현 단계를 따라 진행합니다
4. 완료 후 Lecpin에서 제출합니다

---

<p align="center">
  <sub>Generated by <a href="https://lecpin.com">Lecpin</a></sub>
</p>
`
}
